#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  blueSide1,      sensorDigitalIn)
#pragma config(Sensor, dgtl2,  blueSide2,      sensorDigitalIn)
#pragma config(Sensor, dgtl3,  blueSide3,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  blueBack1,      sensorDigitalIn)
#pragma config(Sensor, dgtl5,  blueBack2,      sensorDigitalIn)
#pragma config(Sensor, dgtl6,  blueBack3,      sensorDigitalIn)
#pragma config(Sensor, dgtl7,  redSide1,       sensorDigitalIn)
#pragma config(Sensor, dgtl8,  redSide2,       sensorDigitalIn)
#pragma config(Sensor, dgtl9,  redSide3,       sensorDigitalIn)
#pragma config(Sensor, dgtl10, redBack1,       sensorDigitalIn)
#pragma config(Sensor, dgtl11, redBack2,       sensorDigitalIn)
#pragma config(Sensor, dgtl12, redBack3,       sensorDigitalIn)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           rightLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLauncher,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           topBelt,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	resetMotorEncoder(frontRight);
	resetMotorEncoder(frontLeft);

	wait1Msec(1000);

	float motorEncoderRight = 1800;
	float motorEncoderLeft = 1800;

	while (nMotorEncoder(frontRight) < motorEncoderRight && nMotorEncoder(frontLeft) < motorEncoderLeft)
	{
		motor[frontRight] = 63;
		motor[frontLeft] = 63;
		motor[backRight] = 63;
		motor[backLeft] = 63;
	}

	motor[frontRight] = 0;
	motor[frontLeft] = 0;
	motor[backRight] = 0;
	motor[backLeft] = 0;
}
